package com.example.epidemic.mapper;

import com.example.epidemic.entity.ReturneesAccessApply;
import com.example.epidemic.entity.ReturneesAccessApplyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ReturneesAccessApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returnees_access_apply
     *
     * @mbg.generated
     */
    long countByExample(ReturneesAccessApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returnees_access_apply
     *
     * @mbg.generated
     */
    int deleteByExample(ReturneesAccessApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returnees_access_apply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String applyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returnees_access_apply
     *
     * @mbg.generated
     */
    int insert(ReturneesAccessApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returnees_access_apply
     *
     * @mbg.generated
     */
    int insertSelective(ReturneesAccessApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returnees_access_apply
     *
     * @mbg.generated
     */
    List<ReturneesAccessApply> selectByExample(ReturneesAccessApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returnees_access_apply
     *
     * @mbg.generated
     */
    ReturneesAccessApply selectByPrimaryKey(String applyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returnees_access_apply
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ReturneesAccessApply record, @Param("example") ReturneesAccessApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returnees_access_apply
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ReturneesAccessApply record, @Param("example") ReturneesAccessApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returnees_access_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ReturneesAccessApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table returnees_access_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ReturneesAccessApply record);
}