package com.example.epidemic.mapper;

import com.example.epidemic.entity.VisitorAccessApply;
import com.example.epidemic.entity.VisitorAccessApplyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface VisitorAccessApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor_access_apply
     *
     * @mbg.generated
     */
    long countByExample(VisitorAccessApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor_access_apply
     *
     * @mbg.generated
     */
    int deleteByExample(VisitorAccessApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor_access_apply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String applyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor_access_apply
     *
     * @mbg.generated
     */
    int insert(VisitorAccessApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor_access_apply
     *
     * @mbg.generated
     */
    int insertSelective(VisitorAccessApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor_access_apply
     *
     * @mbg.generated
     */
    List<VisitorAccessApply> selectByExample(VisitorAccessApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor_access_apply
     *
     * @mbg.generated
     */
    VisitorAccessApply selectByPrimaryKey(String applyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor_access_apply
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") VisitorAccessApply record, @Param("example") VisitorAccessApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor_access_apply
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") VisitorAccessApply record, @Param("example") VisitorAccessApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor_access_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VisitorAccessApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor_access_apply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VisitorAccessApply record);
}