package com.example.epidemic.entity;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.math.BigDecimal;
import java.util.Date;

public class VisitorAccessApply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_access_apply.apply_id
     *
     * @mbg.generated
     */
    private String applyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_access_apply.create_time
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_access_apply.access_time
     *
     * @mbg.generated
     */
    @JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
    private Date accessTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_access_apply.access_type
     *
     * @mbg.generated
     */
    private Byte accessType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_access_apply.resident_id
     *
     * @mbg.generated
     */
    private String residentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_access_apply.resident_name
     *
     * @mbg.generated
     */
    private String residentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_access_apply.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_access_apply.gender
     *
     * @mbg.generated
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_access_apply.id_card
     *
     * @mbg.generated
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_access_apply.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_access_apply.place
     *
     * @mbg.generated
     */
    private String place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_access_apply.temperature
     *
     * @mbg.generated
     */
    private BigDecimal temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_access_apply.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column visitor_access_apply.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor_access_apply.apply_id
     *
     * @return the value of visitor_access_apply.apply_id
     * @mbg.generated
     */
    public String getApplyId() {
        return applyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor_access_apply.apply_id
     *
     * @param applyId the value for visitor_access_apply.apply_id
     * @mbg.generated
     */
    public void setApplyId(String applyId) {
        this.applyId = applyId == null ? null : applyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor_access_apply.create_time
     *
     * @return the value of visitor_access_apply.create_time
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor_access_apply.create_time
     *
     * @param createTime the value for visitor_access_apply.create_time
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor_access_apply.access_time
     *
     * @return the value of visitor_access_apply.access_time
     * @mbg.generated
     */
    public Date getAccessTime() {
        return accessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor_access_apply.access_time
     *
     * @param accessTime the value for visitor_access_apply.access_time
     * @mbg.generated
     */
    public void setAccessTime(Date accessTime) {
        this.accessTime = accessTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor_access_apply.access_type
     *
     * @return the value of visitor_access_apply.access_type
     * @mbg.generated
     */
    public Byte getAccessType() {
        return accessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor_access_apply.access_type
     *
     * @param accessType the value for visitor_access_apply.access_type
     * @mbg.generated
     */
    public void setAccessType(Byte accessType) {
        this.accessType = accessType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor_access_apply.resident_id
     *
     * @return the value of visitor_access_apply.resident_id
     * @mbg.generated
     */
    public String getResidentId() {
        return residentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor_access_apply.resident_id
     *
     * @param residentId the value for visitor_access_apply.resident_id
     * @mbg.generated
     */
    public void setResidentId(String residentId) {
        this.residentId = residentId == null ? null : residentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor_access_apply.resident_name
     *
     * @return the value of visitor_access_apply.resident_name
     * @mbg.generated
     */
    public String getResidentName() {
        return residentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor_access_apply.resident_name
     *
     * @param residentName the value for visitor_access_apply.resident_name
     * @mbg.generated
     */
    public void setResidentName(String residentName) {
        this.residentName = residentName == null ? null : residentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor_access_apply.name
     *
     * @return the value of visitor_access_apply.name
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor_access_apply.name
     *
     * @param name the value for visitor_access_apply.name
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor_access_apply.gender
     *
     * @return the value of visitor_access_apply.gender
     * @mbg.generated
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor_access_apply.gender
     *
     * @param gender the value for visitor_access_apply.gender
     * @mbg.generated
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor_access_apply.id_card
     *
     * @return the value of visitor_access_apply.id_card
     * @mbg.generated
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor_access_apply.id_card
     *
     * @param idCard the value for visitor_access_apply.id_card
     * @mbg.generated
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor_access_apply.phone
     *
     * @return the value of visitor_access_apply.phone
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor_access_apply.phone
     *
     * @param phone the value for visitor_access_apply.phone
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor_access_apply.place
     *
     * @return the value of visitor_access_apply.place
     * @mbg.generated
     */
    public String getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor_access_apply.place
     *
     * @param place the value for visitor_access_apply.place
     * @mbg.generated
     */
    public void setPlace(String place) {
        this.place = place == null ? null : place.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor_access_apply.temperature
     *
     * @return the value of visitor_access_apply.temperature
     * @mbg.generated
     */
    public BigDecimal getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor_access_apply.temperature
     *
     * @param temperature the value for visitor_access_apply.temperature
     * @mbg.generated
     */
    public void setTemperature(BigDecimal temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor_access_apply.remark
     *
     * @return the value of visitor_access_apply.remark
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor_access_apply.remark
     *
     * @param remark the value for visitor_access_apply.remark
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column visitor_access_apply.state
     *
     * @return the value of visitor_access_apply.state
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column visitor_access_apply.state
     *
     * @param state the value for visitor_access_apply.state
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table visitor_access_apply
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", applyId=").append(applyId);
        sb.append(", createTime=").append(createTime);
        sb.append(", accessTime=").append(accessTime);
        sb.append(", accessType=").append(accessType);
        sb.append(", residentId=").append(residentId);
        sb.append(", residentName=").append(residentName);
        sb.append(", name=").append(name);
        sb.append(", gender=").append(gender);
        sb.append(", idCard=").append(idCard);
        sb.append(", phone=").append(phone);
        sb.append(", place=").append(place);
        sb.append(", temperature=").append(temperature);
        sb.append(", remark=").append(remark);
        sb.append(", state=").append(state);
        sb.append("]");
        return sb.toString();
    }
}